# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clickevent',
            old_name='cout',
            new_name='count',
        ),
    ]
