# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 17:10
from __future__ import unicode_literals

import Main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20170717_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aakshyarurl',
            name='url',
            field=models.CharField(max_length=220, validators=[Main.validators.validate_url]),
        ),
    ]
